/****************************************************************************
 *
 *   Copyright (c) 2026 PX4 Development Team. All rights reserved.
 *
 ****************************************************************************/

/**
 * Hnuter controller attitude mode
 *
 * Selects the attitude/torque path used by the Hnuter control backend.
 * 0 uses PX4 mc_att_control + RateControl output. 1 uses the internal
 * geometric attitude error law.
 *
 * @value 0 PX4 rate controller
 * @value 1 Hnuter geometric attitude
 * @min 0
 * @max 1
 * @group Hnuter Control
 */
PARAM_DEFINE_INT32(HNTR_CTRL_MODE, 0);

/**
 * Hnuter vehicle mass
 *
 * @unit kg
 * @min 0.1
 * @max 50.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_MASS, 4.5f);

/**
 * Hnuter maximum thrust per front arm
 *
 * Maximum force generated by one two-motor front arm.
 *
 * @unit N
 * @min 1.0
 * @max 500.0
 * @decimal 1
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_MAX_ARM_T, 170.96f);

/**
 * Hnuter maximum tail thrust
 *
 * @unit N
 * @min 1.0
 * @max 500.0
 * @decimal 1
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_MAX_TAIL_T, 85.48f);

/**
 * Hnuter front arm moment arm
 *
 * @unit m
 * @min 0.01
 * @max 5.0
 * @decimal 3
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_L1, 0.33f);

/**
 * Hnuter tail moment arm
 *
 * @unit m
 * @min 0.01
 * @max 5.0
 * @decimal 3
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_L2, 0.664f);

/**
 * Hnuter roll torque direction
 *
 * Sign used by the custom Hnuter allocator to map normalized roll torque to
 * left/right front-arm thrust. Keep +1 for the real aircraft unless roll
 * correction is physically reversed; use -1 for simulation models whose left
 * and right arm convention is opposite to the hardware convention.
 *
 * @value -1 Reversed
 * @value 1 Normal
 * @min -1
 * @max 1
 * @decimal 0
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_ROLL_SIGN, 1.0f);

/**
 * Hnuter tail pitch torque direction
 *
 * Sign used by the custom Hnuter allocator to map normalized pitch torque to
 * Motor5 reversible thrust. Keep +1 for the real aircraft unless Motor5 pitch
 * correction is physically reversed; use -1 for simulation models whose tail
 * motor thrust axis is opposite to the hardware convention.
 *
 * @value -1 Reversed
 * @value 1 Normal
 * @min -1
 * @max 1
 * @decimal 0
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_TAIL_SIGN, 1.0f);

/**
 * Hnuter tail collective pitch compensation
 *
 * Blends in the old Motor5 compensation for pitch moment caused by collective
 * vertical front thrust and model center-of-mass offset. Keep this at 0 on the
 * real aircraft so Motor5 does not follow throttle. Set to 1 in SITL when the
 * Gazebo model still needs tail thrust to cancel collective pitch moment.
 *
 * @min 0.0
 * @max 1.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_TAIL_COMP, 0.0f);

/**
 * Hnuter legacy hover thrust
 *
 * Retained so existing parameter files still load. The cascaded controller
 * uses HNTR_MOT_HOV for real motor calibration and does not use this value.
 *
 * @min 0.05
 * @max 0.95
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_HOV_THR, 0.65f);

/**
 * Hnuter real-motor hover control
 *
 * Normalized command at which the four front motors together hover the
 * aircraft. With a 1000 to 2000 us PWM range, 0.40 corresponds to 1400 us.
 * This parameter is only used on hardware; SITL uses the Gazebo motor model.
 *
 * @min 0.05
 * @max 0.95
 * @decimal 3
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_MOT_HOV, 0.40f);

/**
 * Hnuter real-motor thrust exponent
 *
 * Exponent in command = hover_command * (force / hover_force)^exponent.
 * A value of 0.5 models thrust proportional to motor speed squared. This
 * parameter is only used on hardware.
 *
 * @min 0.2
 * @max 1.5
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_MOT_EXPO, 0.50f);

/**
 * Hnuter ground-contact motor ratio
 *
 * Mean front-motor command below this fraction of HNTR_MOT_HOV is treated as
 * low thrust by the ground-contact detector. Ground contact additionally
 * requires a commanded descent and no measured vehicle motion.
 *
 * @min 0.5
 * @max 1.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_LND_GC_R, 0.75f);

/**
 * Hnuter landed motor ratio
 *
 * Mean front-motor command below this fraction of HNTR_MOT_HOV satisfies the
 * tighter maybe-landed thrust condition. Keep this below HNTR_LND_GC_R.
 *
 * @min 0.4
 * @max 1.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_LND_MIN_R, 0.60f);

/**
 * Hnuter legacy XY position P gain
 *
 * Retained for parameter-file compatibility. Use HNTR_POS_P_XY.
 * @min 0.0
 * @max 20.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_XY_P, 2.5f);

/**
 * Hnuter legacy Z position P gain
 *
 * Retained for parameter-file compatibility. Use HNTR_POS_P_Z.
 * @min 0.0
 * @max 30.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_Z_P, 8.0f);

/**
 * Hnuter legacy XY velocity gain
 *
 * Retained for parameter-file compatibility. Use HNTR_VEL_P_XY.
 * @min 0.0
 * @max 30.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_XY_D, 1.8f);

/**
 * Hnuter legacy Z velocity gain
 *
 * Retained for parameter-file compatibility. Use HNTR_VEL_P_Z.
 * @min 0.0
 * @max 30.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_Z_D, 4.0f);

/**
 * Hnuter legacy XY position I gain
 *
 * Retained for parameter-file compatibility. The cascaded controller does not
 * integrate position error; use HNTR_VEL_I_XY for velocity integral action.
 * @min 0.0
 * @max 10.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_XY_I, 0.0f);

/**
 * Hnuter legacy Z position I gain
 *
 * Retained for parameter-file compatibility. The cascaded controller does not
 * integrate position error; use HNTR_VEL_I_Z for velocity integral action.
 * @min 0.0
 * @max 20.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_Z_I, 3.0f);

/**
 * Hnuter XY position-loop P gain
 *
 * Converts horizontal position error to a velocity correction.
 *
 * @min 0.0
 * @max 10.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_POS_P_XY, 1.0f);

/**
 * Hnuter Z position-loop P gain
 *
 * Converts vertical position error to a velocity correction.
 *
 * @min 0.0
 * @max 10.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_POS_P_Z, 1.5f);

/**
 * Hnuter XY velocity-loop P gain
 *
 * @min 0.0
 * @max 30.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_VEL_P_XY, 2.5f);

/**
 * Hnuter Z velocity-loop P gain
 *
 * @min 0.0
 * @max 30.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_VEL_P_Z, 3.0f);

/**
 * Hnuter XY velocity-loop I gain
 *
 * @min 0.0
 * @max 10.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_VEL_I_XY, 0.20f);

/**
 * Hnuter Z velocity-loop I gain
 *
 * @min 0.0
 * @max 10.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_VEL_I_Z, 0.50f);

/**
 * Hnuter XY velocity-loop acceleration damping
 *
 * Feedback gain on measured horizontal acceleration.
 *
 * @min 0.0
 * @max 10.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_VEL_D_XY, 0.20f);

/**
 * Hnuter Z velocity-loop acceleration damping
 *
 * Feedback gain on measured vertical acceleration.
 *
 * @min 0.0
 * @max 10.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_VEL_D_Z, 0.30f);

/**
 * Hnuter XY velocity integrator limit
 *
 * @unit m/s^2
 * @min 0.0
 * @max 30.0
 * @decimal 1
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_VEL_ILIM_XY, 2.0f);

/**
 * Hnuter Z velocity integrator limit
 *
 * @unit m/s^2
 * @min 0.0
 * @max 30.0
 * @decimal 1
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_VEL_ILIM_Z, 3.0f);

/**
 * Hnuter maximum horizontal velocity setpoint
 *
 * @unit m/s
 * @min 0.0
 * @max 30.0
 * @decimal 1
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_VEL_XY, 5.0f);

/**
 * Hnuter maximum upward velocity setpoint
 *
 * @unit m/s
 * @min 0.0
 * @max 20.0
 * @decimal 1
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_VEL_UP, 3.0f);

/**
 * Hnuter maximum downward velocity setpoint
 *
 * @unit m/s
 * @min 0.0
 * @max 20.0
 * @decimal 1
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_VEL_DN, 1.5f);

/**
 * Hnuter XY acceleration limit
 *
 * @unit m/s^2
 * @min 0.1
 * @max 100.0
 * @decimal 1
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_ACC_XY, 20.0f);

/**
 * Hnuter Z acceleration limit
 *
 * @unit m/s^2
 * @min 0.1
 * @max 100.0
 * @decimal 1
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_ACC_Z, 65.0f);

/**
 * Hnuter Stabilized altitude P gain
 *
 * Used only by Hnuter manual attitude-altitude mode. Stabilized mode does not
 * use XY position control; this gain holds the current height.
 *
 * @min 0.0
 * @max 30.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_STAB_Z_P, 3.0f);

/**
 * Hnuter Stabilized altitude velocity damping
 *
 * @min 0.0
 * @max 30.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_STAB_Z_D, 2.0f);

/**
 * Hnuter Stabilized altitude I gain
 *
 * @min 0.0
 * @max 10.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_STAB_Z_I, 0.5f);

/**
 * Hnuter Stabilized vertical acceleration limit
 *
 * @unit m/s^2
 * @min 0.1
 * @max 100.0
 * @decimal 1
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_STAB_ACC_Z, 8.0f);

/**
 * Hnuter Stabilized maximum altitude setpoint slew rate
 *
 * Positive throttle stick raises the altitude setpoint. Center stick holds
 * the current altitude.
 *
 * @unit m/s
 * @min 0.0
 * @max 10.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_STAB_Z_VEL, 0.8f);

/**
 * Hnuter Stabilized throttle center deadband
 *
 * @min 0.0
 * @max 0.8
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_STAB_THR_DB, 0.15f);

/**
 * Hnuter normal tilt force limit
 *
 * @unit deg
 * @min 0.0
 * @max 185.0
 * @decimal 1
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_TILT_MAX, 185.0f);

/**
 * Hnuter takeoff tilt suppression time
 *
 * @unit s
 * @min 0.0
 * @max 10.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_TO_SUP_T, 1.0f);

/**
 * Hnuter takeoff XY lock end time
 *
 * @unit s
 * @min 0.0
 * @max 20.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_TO_LOCK_T, 3.0f);

/**
 * Hnuter takeoff tilt limit
 *
 * @unit deg
 * @min 0.0
 * @max 185.0
 * @decimal 1
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_TO_TILT, 20.0f);

/**
 * Hnuter XY lock tilt limit
 *
 * @unit deg
 * @min 0.0
 * @max 185.0
 * @decimal 1
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_LOCK_TILT, 30.0f);

/**
 * Hnuter XY lock acceleration limit
 *
 * @unit m/s^2
 * @min 0.1
 * @max 100.0
 * @decimal 1
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_LOCK_ACC, 3.0f);

/**
 * Hnuter XY lock position gain scale
 *
 * @min 0.0
 * @max 1.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_LOCK_KP, 0.8f);

/**
 * Hnuter geometric roll attitude gain
 *
 * @min 0.0
 * @max 20.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_ATT_KR_R, 1.5f);

/**
 * Hnuter geometric pitch attitude gain
 *
 * @min 0.0
 * @max 20.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_ATT_KR_P, 1.5f);

/**
 * Hnuter geometric yaw attitude gain
 *
 * @min 0.0
 * @max 20.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_ATT_KR_Y, 1.5f);

/**
 * Hnuter geometric roll rate damping
 *
 * @min 0.0
 * @max 20.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_ATT_D_R, 1.2f);

/**
 * Hnuter geometric pitch rate damping
 *
 * @min 0.0
 * @max 20.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_ATT_D_P, 1.2f);

/**
 * Hnuter geometric yaw rate damping
 *
 * @min 0.0
 * @max 20.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_ATT_D_Y, 1.2f);

/**
 * Hnuter geometric roll attitude integral gain
 *
 * @min 0.0
 * @max 20.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_ATT_I_R, 0.0f);

/**
 * Hnuter geometric pitch attitude integral gain
 *
 * Integral pitch attitude gain used to remove steady pitch error from CG offset
 * or tail rotor trim mismatch. Keep this low during bench tuning.
 *
 * @min 0.0
 * @max 20.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_ATT_I_P, 0.0f);

/**
 * Hnuter geometric yaw attitude integral gain
 *
 * @min 0.0
 * @max 20.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_ATT_I_Y, 0.0f);

/**
 * Hnuter geometric roll integral torque limit
 *
 * @unit Nm
 * @min 0.0
 * @max 50.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_ATT_ILIM_R, 1.0f);

/**
 * Hnuter geometric pitch integral torque limit
 *
 * Maximum pitch torque contribution from the pitch attitude integral term.
 *
 * @unit Nm
 * @min 0.0
 * @max 50.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_ATT_ILIM_P, 3.0f);

/**
 * Hnuter geometric yaw integral torque limit
 *
 * @unit Nm
 * @min 0.0
 * @max 50.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_ATT_ILIM_Y, 1.0f);

/**
 * Hnuter geometric roll torque limit
 *
 * @min 0.0
 * @max 100.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_TAU_R, 0.9f);

/**
 * Hnuter geometric pitch torque limit
 *
 * @min 0.0
 * @max 100.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_TAU_P, 0.9f);

/**
 * Hnuter geometric yaw torque limit
 *
 * @min 0.0
 * @max 100.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_TAU_Y, 1.8f);

/**
 * Hnuter pitch torque bias
 *
 * Constant normalized pitch torque added after the pitch attitude controller.
 * This is used to trim a rear/front CG offset so Motor5 does not have to sit at
 * the bidirectional ESC neutral point in level attitude. Positive values move
 * Motor5 toward the positive pitch-torque direction; use the opposite sign if
 * pitch trim moves the vehicle the wrong way.
 *
 * @min -1.0
 * @max 1.0
 * @decimal 3
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_PITCH_BIAS, 0.0f);

/**
 * Enable Hnuter RC attitude hold channels
 *
 * Uses AUX1 as roll-rate command, AUX2 as pitch-rate command and the rising
 * edge of AUX3 to start a gradual return to level. This is active only in
 * manual position/velocity control modes; Offboard and Stabilized are not
 * overridden.
 *
 * @boolean
 * @group Hnuter Control
 */
PARAM_DEFINE_INT32(HNTR_RC_ATT_EN, 0);

/**
 * Hnuter AUX1 maximum roll command rate
 *
 * @unit deg/s
 * @min 0.0
 * @max 360.0
 * @decimal 1
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_RC_RATE_R, 30.0f);

/**
 * Hnuter AUX2 maximum pitch command rate
 *
 * @unit deg/s
 * @min 0.0
 * @max 360.0
 * @decimal 1
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_RC_RATE_P, 30.0f);

/**
 * Hnuter yaw stick maximum command rate
 *
 * In manual position modes the yaw stick integrates an internal heading
 * setpoint. Centering the stick holds the current heading setpoint instead of
 * accepting a trajectory yaw value that follows estimator drift.
 *
 * @unit deg/s
 * @min 0.0
 * @max 360.0
 * @decimal 1
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_RC_RATE_Y, 30.0f);

/**
 * Hnuter auxiliary attitude channel deadband
 *
 * @min 0.0
 * @max 0.5
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_RC_DB, 0.08f);

/**
 * Hnuter RC held attitude limit
 *
 * Maximum absolute roll and pitch setpoint accumulated from AUX1 and AUX2.
 *
 * @unit deg
 * @min 0.0
 * @max 180.0
 * @decimal 1
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_RC_ANG_MAX, 90.0f);

/**
 * Hnuter gradual return-to-level rate
 *
 * Maximum roll and pitch setpoint slew rate after an AUX3 rising edge.
 *
 * @unit deg/s
 * @min 1.0
 * @max 180.0
 * @decimal 1
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_RC_LVL_R, 20.0f);
