/****************************************************************************
 *
 *   Copyright (c) 2026 PX4 Development Team. All rights reserved.
 *
 ****************************************************************************/

/**
 * Hnuter controller attitude mode
 *
 * Selects the attitude/torque path used by the Hnuter control backend.
 * 0 uses PX4 mc_att_control + RateControl output. 1 uses the internal
 * geometric attitude error law.
 *
 * @value 0 PX4 rate controller
 * @value 1 Hnuter geometric attitude
 * @min 0
 * @max 1
 * @group Hnuter Control
 */
PARAM_DEFINE_INT32(HNTR_CTRL_MODE, 0);

/**
 * Hnuter vehicle mass
 *
 * @unit kg
 * @min 0.1
 * @max 50.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_MASS, 4.5f);

/**
 * Hnuter maximum thrust per front arm
 *
 * Maximum force generated by one two-motor front arm.
 *
 * @unit N
 * @min 1.0
 * @max 500.0
 * @decimal 1
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_MAX_ARM_T, 170.96f);

/**
 * Hnuter maximum tail thrust
 *
 * @unit N
 * @min 1.0
 * @max 500.0
 * @decimal 1
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_MAX_TAIL_T, 85.48f);

/**
 * Hnuter front arm moment arm
 *
 * @unit m
 * @min 0.01
 * @max 5.0
 * @decimal 3
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_L1, 0.33f);

/**
 * Hnuter tail moment arm
 *
 * @unit m
 * @min 0.01
 * @max 5.0
 * @decimal 3
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_L2, 0.664f);

/**
 * Hnuter hover thrust
 *
 * Normalized collective thrust corresponding to vehicle weight in the Hnuter
 * force-to-thrust map. Raising this value makes Position mode command higher
 * PWM for the same physical hover force.
 *
 * @min 0.05
 * @max 0.95
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_HOV_THR, 0.65f);

/**
 * Hnuter XY position P gain
 *
 * @min 0.0
 * @max 20.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_XY_P, 2.5f);

/**
 * Hnuter Z position P gain
 *
 * @min 0.0
 * @max 30.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_Z_P, 8.0f);

/**
 * Hnuter XY velocity D gain
 *
 * @min 0.0
 * @max 30.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_XY_D, 1.8f);

/**
 * Hnuter Z velocity D gain
 *
 * @min 0.0
 * @max 30.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_Z_D, 4.0f);

/**
 * Hnuter XY position I gain
 *
 * @min 0.0
 * @max 10.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_XY_I, 0.0f);

/**
 * Hnuter Z position I gain
 *
 * @min 0.0
 * @max 20.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_Z_I, 3.0f);

/**
 * Hnuter XY acceleration limit
 *
 * @unit m/s^2
 * @min 0.1
 * @max 100.0
 * @decimal 1
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_ACC_XY, 20.0f);

/**
 * Hnuter Z acceleration limit
 *
 * @unit m/s^2
 * @min 0.1
 * @max 100.0
 * @decimal 1
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_ACC_Z, 65.0f);

/**
 * Hnuter normal tilt force limit
 *
 * @unit deg
 * @min 0.0
 * @max 185.0
 * @decimal 1
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_TILT_MAX, 185.0f);

/**
 * Hnuter takeoff tilt suppression time
 *
 * @unit s
 * @min 0.0
 * @max 10.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_TO_SUP_T, 1.0f);

/**
 * Hnuter takeoff XY lock end time
 *
 * @unit s
 * @min 0.0
 * @max 20.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_TO_LOCK_T, 3.0f);

/**
 * Hnuter takeoff tilt limit
 *
 * @unit deg
 * @min 0.0
 * @max 185.0
 * @decimal 1
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_TO_TILT, 20.0f);

/**
 * Hnuter XY lock tilt limit
 *
 * @unit deg
 * @min 0.0
 * @max 185.0
 * @decimal 1
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_LOCK_TILT, 30.0f);

/**
 * Hnuter XY lock acceleration limit
 *
 * @unit m/s^2
 * @min 0.1
 * @max 100.0
 * @decimal 1
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_LOCK_ACC, 3.0f);

/**
 * Hnuter XY lock position gain scale
 *
 * @min 0.0
 * @max 1.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_LOCK_KP, 0.8f);

/**
 * Hnuter geometric roll attitude gain
 *
 * @min 0.0
 * @max 20.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_ATT_KR_R, 1.5f);

/**
 * Hnuter geometric pitch attitude gain
 *
 * @min 0.0
 * @max 20.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_ATT_KR_P, 1.5f);

/**
 * Hnuter geometric yaw attitude gain
 *
 * @min 0.0
 * @max 20.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_ATT_KR_Y, 1.5f);

/**
 * Hnuter geometric roll rate damping
 *
 * @min 0.0
 * @max 20.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_ATT_D_R, 1.2f);

/**
 * Hnuter geometric pitch rate damping
 *
 * @min 0.0
 * @max 20.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_ATT_D_P, 1.2f);

/**
 * Hnuter geometric yaw rate damping
 *
 * @min 0.0
 * @max 20.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_ATT_D_Y, 1.2f);

/**
 * Hnuter geometric roll torque limit
 *
 * @min 0.0
 * @max 100.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_TAU_R, 0.9f);

/**
 * Hnuter geometric pitch torque limit
 *
 * @min 0.0
 * @max 100.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_TAU_P, 0.9f);

/**
 * Hnuter geometric yaw torque limit
 *
 * @min 0.0
 * @max 100.0
 * @decimal 2
 * @group Hnuter Control
 */
PARAM_DEFINE_FLOAT(HNTR_TAU_Y, 1.8f);
